version: '3.7'
services:
  ponosdb:
    container_name: ponosdb
    image: postgres:15
    env_file:
      - ./app/db/.env
    volumes:
       - ponosdb_data:/pg
    ports:
      - 100.111.31.32:12000:5432
    restart: unless-stopped
  
  ponosfront:
    container_name: ponosfront
    env_file:
      - ./app/front/.env
    build:
      dockerfile: Dockerfile
      context: ./app/front
    ports:
      - 100.111.31.32:3000:3000
    restart: unless-stopped

  ponosapi:
    container_name: ponosapi
    build:
      dockerfile: Dockerfile
      context: ./app/api
    ports:
      - 100.111.31.32:8080:8080
    restart: unless-stopped

  ponostunnel:
    container_name: ponostunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TOKEN}

volumes:
  ponosdb_data:
